function iconsHtml(){
	return '<div class="fa col-sm-12">'+
				'<input type="radio" name="icons" value="" checked> <i class="fa"> 无图标</i><br/>'+
				'<input type="radio" name="icons" value="icon-adjust"> <i class="icon-adjust">icon-adjust</i><br/>'+
			    '<input type="radio" name="icons" value="icon-adjust-asterisk"> <i class="icon-asterisk">icon-asterisk</i><br/>'+
			    '<input type="radio" name="icons" value="icon-ban-circle"> <i class="icon-ban-circle">icon-ban-circle </i><br/>'+
			    '<input type="radio" name="icons" value="icon-bar-chart"> <i class="icon-bar-chart"> icon-bar-chart </i><br/>'+
			    '<input type="radio" name="icons" value="icon-barcode"> <i class="icon-barcode"> icon-barcode </i><br/>'+
			    '<input type="radio" name="icons" value="icon-beaker"> <i class="icon-beaker"> icon-beaker </i><br/>'+
			    '<input type="radio" name="icons" value="icon-beer"> <i class="icon-beer"> icon-beer </i><br/>'+
			    '<input type="radio" name="icons" value="icon-bell"> <i class="icon-bell"> icon-bell </i><br/>'+
			    '<input type="radio" name="icons" value="icon-bell-alt"> <i class="icon-bell-alt"> icon-bell-alt </i><br/>'+
			    '<input type="radio" name="icons" value="icon-bolt"> <i class="icon-bolt"> icon-bolt </i><br/>'+
			    '<input type="radio" name="icons" value="icon-book"> <i class="icon-book"> icon-book </i><br/>'+
			    '<input type="radio" name="icons" value="icon-bookmark"> <i class="icon-bookmark"> icon-bookmark </i><br/>'+
			    '<input type="radio" name="icons" value="icon-bookmark-empty"> <i class="icon-bookmark-empty"> icon-bookmark-empty </i><br/>'+
			    '<input type="radio" name="icons" value="icon-briefcase"> <i class="icon-briefcase"> icon-briefcase </i><br/>'+
			    '<input type="radio" name="icons" value="icon-bullhorn"> <i class="icon-bullhorn"> icon-bullhorn </i><br/>'+
			    '<input type="radio" name="icons" value="icon-calendar"> <i class="icon-calendar"> icon-calendar </i><br/>'+
			    '<input type="radio" name="icons" value="icon-camera"> <i class="icon-camera"> icon-camera </i><br/>'+
			    '<input type="radio" name="icons" value="icon-camera-retro"> <i class="icon-camera-retro"> icon-camera-retro </i><br/>'+
			    '<input type="radio" name="icons" value="icon-certificate"> <i class="icon-certificate"> icon-certificate </i><br/>'+
			    '<input type="radio" name="icons" value="icon-check"> <i class="icon-check"> icon-check </i><br/>'+
			    '<input type="radio" name="icons" value="icon-check-empty"> <i class="icon-check-empty"> icon-check-empty </i><br/>'+
			    '<input type="radio" name="icons" value="icon-circle"> <i class="icon-circle"> icon-circle </i><br/>'+
			    '<input type="radio" name="icons" value="icon-circle-blank"> <i class="icon-circle-blank"> icon-circle-blank </i><br/>'+
			    '<input type="radio" name="icons" value="icon-cloud"> <i class="icon-cloud"> icon-cloud </i><br/>'+
			    '<input type="radio" name="icons" value="icon-cloud-download"> <i class="icon-cloud-download"> icon-cloud-download </i><br/>'+
			    '<input type="radio" name="icons" value="icon-cloud-upload"> <i class="icon-cloud-upload"> icon-cloud-upload </i><br/>'+
			    '<input type="radio" name="icons" value="icon-coffee"> <i class="icon-coffee"> icon-coffee </i><br/>'+
			    '<input type="radio" name="icons" value="icon-cog"> <i class="icon-cog"> icon-cog </i><br/>'+
			    '<input type="radio" name="icons" value="icon-cogs"> <i class="icon-cogs"> icon-cogs </i><br/>'+
			    '<input type="radio" name="icons" value="icon-comment"> <i class="icon-comment"> icon-comment </i><br/>'+
			    '<input type="radio" name="icons" value="icon-comment-alt"> <i class="icon-comment-alt"> icon-comment-alt </i><br/>'+
			    '<input type="radio" name="icons" value="icon-comments"> <i class="icon-comments"> icon-comments </i><br/>'+
			    '<input type="radio" name="icons" value="icon-comments-alt"> <i class="icon-comments-alt"> icon-comments-alt </i><br/>'+
			    '<input type="radio" name="icons" value="icon-credit-card"> <i class="icon-credit-card"> icon-credit-card </i><br/>'+
			    '<input type="radio" name="icons" value="icon-dashboard"> <i class="icon-dashboard"> icon-dashboard </i><br/>'+
			    '<input type="radio" name="icons" value="icon-desktop"> <i class="icon-desktop"> icon-desktop </i><br/>'+
			    '<input type="radio" name="icons" value="icon-download"> <i class="icon-download"> icon-download </i><br/>'+
			    '<input type="radio" name="icons" value="icon-download-alt"> <i class="icon-download-alt"> icon-download-alt </i><br/>'+
			    '<input type="radio" name="icons" value="icon-edit"> <i class="icon-edit"> icon-edit </i><br/>'+
			    '<input type="radio" name="icons" value="icon-envelope"> <i class="icon-envelope"> icon-envelope </i><br/>'+
			    '<input type="radio" name="icons" value="icon-envelope-alt"> <i class="icon-envelope-alt"> icon-envelope-alt </i><br/>'+
			    '<input type="radio" name="icons" value="icon-exchange"> <i class="icon-exchange"> icon-exchange </i><br/>'+
			    '<input type="radio" name="icons" value="icon-exclamation-sign"> <i class="icon-exclamation-sign"> icon-exclamation-sign </i><br/>'+
			    '<input type="radio" name="icons" value="icon-external-link"> <i class="icon-external-link"> icon-external-link </i><br/>'+
			    '<input type="radio" name="icons" value="icon-eye-close"> <i class="icon-eye-close"> icon-eye-close </i><br/>'+
			    '<input type="radio" name="icons" value="icon-eye-open"> <i class="icon-eye-open"> icon-eye-open </i><br/>'+
			    '<input type="radio" name="icons" value="icon-facetime-video"> <i class="icon-facetime-video"> icon-facetime-video </i><br/>'+
			    '<input type="radio" name="icons" value="icon-fighter-jet"> <i class="icon-fighter-jet"> icon-fighter-jet </i><br/>'+
			    '<input type="radio" name="icons" value="icon-film"> <i class="icon-film"> icon-film </i><br/>'+
			    '<input type="radio" name="icons" value="icon-filter"> <i class="icon-filter"> icon-filter </i><br/>'+
			    '<input type="radio" name="icons" value="icon-fire"> <i class="icon-fire"> icon-fire </i><br/>'+
			    '<input type="radio" name="icons" value="icon-flag"> <i class="icon-flag"> icon-flag </i><br/>'+
			    '<input type="radio" name="icons" value="icon-folder-close"> <i class="icon-folder-close"> icon-folder-close </i><br/>'+
			    '<input type="radio" name="icons" value="icon-folder-ope"> <i class="icon-folder-ope"> icon-folder-ope </i><br/>'+
			    '<input type="radio" name="icons" value="icon-folder-close-alt"> <i class="icon-folder-close-alt"> icon-folder-close-alt </i><br/>'+
			    '<input type="radio" name="icons" value="icon-folder-open-alt"> <i class="icon-folder-open-alt"> icon-folder-open-alt </i><br/>'+
			    '<input type="radio" name="icons" value="icon-food"> <i class="icon-food"> icon-food </i><br/>'+
			    '<input type="radio" name="icons" value="icon-gift"> <i class="icon-gift"> icon-gift </i><br/>'+
			    '<input type="radio" name="icons" value="icon-glass"> <i class="icon-glass"> icon-glass </i><br/>'+
			    '<input type="radio" name="icons" value="icon-globe"> <i class="icon-globe"> icon-globe </i><br/>'+
			    '<input type="radio" name="icons" value="icon-group"> <i class="icon-group"> icon-group </i><br/>'+
			    '<input type="radio" name="icons" value="icon-hdd"> <i class="icon-hdd"> icon-hdd </i><br/>'+
			    '<input type="radio" name="icons" value="icon-headphones"> <i class="icon-headphones"> icon-headphones </i><br/>'+
			    '<input type="radio" name="icons" value="icon-heart"> <i class="icon-heart"> icon-heart </i><br/>'+
			    '<input type="radio" name="icons" value="icon-heart-empty"> <i class="icon-heart-empty"> icon-heart-empty </i><br/>'+
			    '<input type="radio" name="icons" value="icon-home"> <i class="icon-home"> icon-home </i><br/>'+
			    '<input type="radio" name="icons" value="icon-inbox"> <i class="icon-inbox"> icon-inbox </i><br/>'+
			    '<input type="radio" name="icons" value="icon-info-sign"> <i class="icon-info-sign"> icon-info-sign </i><br/>'+
			    '<input type="radio" name="icons" value="icon-key"> <i class="icon-key"> icon-key </i><br/>'+
			    '<input type="radio" name="icons" value="icon-leaf"> <i class="icon-leaf"> icon-leaf </i><br/>'+
			    '<input type="radio" name="icons" value="icon-laptop"> <i class="icon-laptop"> icon-laptop </i><br/>'+
			    '<input type="radio" name="icons" value="icon-legal"> <i class="icon-legal"> icon-legal </i><br/>'+
			    '<input type="radio" name="icons" value="icon-lemon"> <i class="icon-lemon"> icon-lemon </i><br/>'+
			    '<input type="radio" name="icons" value="icon-lightbulb"> <i class="icon-lightbulb"> icon-lightbulb </i><br/>'+
			    '<input type="radio" name="icons" value="icon-lock"> <i class="icon-lock"> icon-lock </i><br/>'+
			    '<input type="radio" name="icons" value="icon-user"> <i class="icon-user"> icon-user </i><br/>'+
			    '<input type="radio" name="icons" value="icon-unlock"> <i class="icon-unlock"> icon-unlock </i><br/></div>';
}
